'''
    WEEK 02 - PROGRAM 03: GUESSING OF RANDOM NUMBERS
    
    Create a program that allows the system to generate a random number between [1, 200], 
    and the user has the required attempts to enter numbers until he can guess the number generated by the system.
    - If the user guesses correctly, the system should allow him to continue the game to guess new random numbers;
    - Otherwise, the system should indicate whether the number entered by the user is greater or less 
      than the random number generated by the system.

    Definition of variables:
        - n: random number generated by system
        - guess: number input by the user to try guess random number n
        - play: option to continuing play or not [Y|N]

'''

import random

def generate_random_number():    
    return random.randint(1, 200)


def get_user_guess():
    while True:
        try:
            guess = int(input("Guess the number: "))
            return guess
        except ValueError:
            print("Invalid input. Please enter a valid integer.")


def play_round():    
    number_to_guess = generate_random_number()
    
    while True:
        guess = get_user_guess()
        
        if guess < number_to_guess:
            print("Too low... please try again.\n")
        elif guess > number_to_guess:
            print("Too high... please try again.\n")
        else:
            print(f"You guessed the number! n = {number_to_guess}\n")
            break


def play_game():
    print("=== GUESSING GAME ===")
    
    while True:
        play_round()
        play_again = input("Want to play again [Y|N]? ").strip().lower()
        
        if play_again != 'y':
            print("Game is finished!")
            break


# Run the game
if __name__ == "__main__":
    play_game()
